# Generated by Django 4.2 on 2025-01-12 04:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('cliente_id', models.PositiveIntegerField(unique=True, verbose_name='ID del Cliente')),
                ('num_ruta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Ruta')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección Principal')),
                ('direccion_otra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Alternativa')),
                ('barrio', models.CharField(max_length=30, verbose_name='Barrio')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('referencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha del Préstamo')),
                ('saldo', models.IntegerField(verbose_name='Saldo')),
                ('prestamo', models.IntegerField(verbose_name='Monto del Préstamo')),
                ('forma_pago', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], max_length=20, verbose_name='Forma de Pago')),
                ('numero_cuotas', models.PositiveIntegerField(verbose_name='Número de Cuotas')),
                ('num_cuotas_pagadas', models.PositiveIntegerField(verbose_name='Número de Cuotas')),
                ('estado', models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente'), ('activo', 'Activo')], default='activo', max_length=20, verbose_name='Estado')),
                ('cuotas_atrasadas', models.PositiveIntegerField(default=0, verbose_name='Cuotas Atrasadas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='gestion.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Gasto')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor del Gasto')),
                ('fecha', models.DateField(verbose_name='Fecha del Gasto')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('cobrador', 'Cobrador')], max_length=30, unique=True, verbose_name='Rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('fecha_pagada', models.DateField(blank=True, null=True, verbose_name='Fecha Pagada')),
                ('valor', models.IntegerField(verbose_name='Valor de la Cuota')),
                ('valor_cancelado', models.IntegerField(blank=True, null=True, verbose_name='Valor Cancelado')),
                ('num_cuotas', models.PositiveIntegerField(verbose_name='Número de Cuotas')),
                ('estado', models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente de pago'), ('activo', 'Activo')], default='activo', max_length=20, verbose_name='Estado')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='gestion.credito', verbose_name='Crédito')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_inicial', models.PositiveIntegerField(verbose_name='Capital Inicial')),
                ('capital_prestado', models.PositiveIntegerField(verbose_name='Capital Prestado')),
                ('capital_cancelado', models.PositiveIntegerField(verbose_name='Capital Cancelado')),
                ('capital_disponible', models.PositiveIntegerField(verbose_name='Capital Disponible')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
